name: macOS CI

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    name: Build on macOS
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    # Cache dependencies - using newer actions/cache@v3
    - name: Cache Rust dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
    
    # Build default version
    - name: Build (Default)
      run: cargo build --release
    
    # Build with NVIDIA GPU support
    - name: Build (NVIDIA GPU)
      run: cargo build --release --features nvidia-gpu
        
    # Prepare directories and binaries
    - name: Prepare binaries
      run: |
        mkdir -p artifacts/default artifacts/nvidia
        cp target/release/ezstats artifacts/default/
        cp target/release/ezstats artifacts/nvidia/ezstats-nvidia
    
    # Package artifacts
    - name: Package artifacts
      run: |
        cd artifacts
        tar -czvf ../ezstats-default.tar.gz default
        tar -czvf ../ezstats-nvidia.tar.gz nvidia
    
    # Upload artifacts
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ezstats-macos-x86_64
        path: |
          ezstats-default.tar.gz
          ezstats-nvidia.tar.gz
    
    # Create release if this is a tag
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v')
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    
    # Upload release assets if this is a tag
    - name: Upload Release Assets
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ezstats-default.tar.gz
        asset_name: ezstats-macos-x86_64-default.tar.gz
        asset_content_type: application/gzip